### ISSUE TITLE
Installing the current alpha fails with: Cannot find module 'mini-css-extract-plugin'

### ISSUE THREAD

**Issue by pbauer** [plone/volto#5902]
Starting a project `myproject` and use the latest Alpha (Volto 18.0.0-alpha.23, Volto Generator 9.0.0-alpha.9) fails with 

```
Cannot find module 'mini-css-extract-plugin'
```

Steps to reproduce:

```
$ pipx run cookiecutter gh:collective/cookiecutter-plone-starter

⚠️  cookiecutter is already on your PATH and installed at /Users/pbauer/.pyenv/shims/cookiecutter. Downloading and running anyway.
You've downloaded /Users/pbauer/.cookiecutters/cookiecutter-plone-starter before. Is it okay to delete and re-download it? [y/n] (y):

Cookiecutter Plone Starter
================================================================================

Sanity checks
--------------------------------------------------------------------------------
  [1/5] Python: ✓
  [2/5] Node: ✓
  [3/5] yo: ✓
  [4/5] Docker: ✓
  [5/5] git: ✓

Project details
--------------------------------------------------------------------------------

  [1/19] Project Title (Project Title): myproject
  [2/19] Project Description (A new project using Plone 6.):
  [3/19] Project Slug (Used for repository id) (myproject):
  [4/19] Project URL (without protocol) (myproject.example.com):
  [5/19] Author (Plone Foundation):
  [6/19] Author E-mail (collective@plone.org):
  [7/19] Python Package Name (myproject):
  [8/19] Volto Addon Name (volto-myproject):
  [9/19] Choose a Python Test Framework
    1 - pytest
    2 - unittest
    Choose from [1/2] (1):
  [10/19] Plone Version (6.0.10):
  [11/19] Should we use Volto Alpha Versions? (No): Yes
  [12/19] Volto Version (18.0.0-alpha.23):
  [13/19] Volto Generator Version (9.0.0-alpha.9):
  [14/19] Language
    1 - English
    2 - Deutsch
    3 - Español
    4 - Português (Brasil)
    5 - Nederlands
    6 - Suomi
    Choose from [1/2/3/4/5/6] (1): 1
  [15/19] GitHub Username or Organization (collective):
  [16/19] Container Registry
    1 - GitHub Container Registry
    2 - Docker Hub
    Choose from [1/2] (1):
  [17/19] Should we setup a caching server?
    1 - Yes
    2 - No
    Choose from [1/2] (1):
  [18/19] Add Ansible playbooks?
    1 - Yes
    2 - No
    Choose from [1/2] (1):
  [19/19] Add GitHub Action to Deploy this project?
    1 - Yes
    2 - No
    Choose from [1/2] (1):

myproject generation
--------------------------------------------------------------------------------

Summary:
  - Plone version: 6.0.10
  - Volto version: 18.0.0-alpha.23
  - Volto Generator version: 9.0.0-alpha.9
  - Output folder: /Users/pbauer/workspace/test/myproject

Frontend codebase:
 - Generate frontend application with @plone/volto 18.0.0-alpha.23

Backend codebase
 - Remove folder src/myproject/src/myproject/tests not used by pytest
 - Format generated code in the backend

================================================================================
```

Installation seems to work:
```
$ cd myproject/frontend
$ make install

Install frontend

Using src/addons
Update paths in tsconfig.json

➤ YN0000: ┌ Resolution step
➤ YN0061: │ @babel/plugin-proposal-nullish-coalescing-operator@npm:7.18.6 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
➤ YN0061: │ @babel/plugin-proposal-private-property-in-object@npm:7.21.11 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-private-property-in-object instead.
➤ YN0061: │ @babel/plugin-proposal-private-methods@npm:7.18.6 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-private-methods instead.
➤ YN0061: │ @babel/plugin-proposal-numeric-separator@npm:7.18.6 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
➤ YN0061: │ @babel/plugin-proposal-optional-chaining@npm:7.21.0 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
➤ YN0061: │ stable@npm:0.1.8 is deprecated: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
➤ YN0061: │ @babel/plugin-proposal-class-properties@npm:7.18.6 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
➤ YN0061: │ @babel/plugin-proposal-object-rest-spread@npm:7.20.7 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
➤ YN0061: │ uuid-browser@npm:3.1.0 is deprecated: Package no longer supported and required. Use the uuid package or crypto.randomUUID instead
➤ YN0061: │ babel-plugin-react-intl@npm:5.1.17 is deprecated: this package has been renamed to babel-plugin-formatjs
➤ YN0061: │ superagent@npm:3.8.2 is deprecated: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
➤ YN0061: │ figgy-pudding@npm:3.5.2 is deprecated: This module is no longer supported.
➤ YN0061: │ @npmcli/move-file@npm:1.1.2 is deprecated: This functionality has been moved to @npmcli/fs
➤ YN0061: │ querystring@npm:0.2.1 is deprecated: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
➤ YN0061: │ chokidar@npm:2.1.8 is deprecated: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
➤ YN0061: │ source-map-resolve@npm:0.5.3 is deprecated: See https://github.com/lydell/source-map-resolve#deprecated
➤ YN0032: │ fsevents@npm:2.3.3: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ fsevents@npm:1.2.13 is deprecated: The v1 package contains DANGEROUS / INSECURE binaries. Upgrade to safe fsevents v2
➤ YN0061: │ intl-messageformat-parser@npm:3.6.4 is deprecated: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser
➤ YN0061: │ core-js@npm:2.6.12 is deprecated: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
➤ YN0061: │ formidable@npm:1.2.6 is deprecated: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
➤ YN0061: │ mini-create-react-context@npm:0.4.1 is deprecated: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
➤ YN0061: │ sane@npm:4.1.0 is deprecated: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
➤ YN0061: │ urix@npm:0.1.0 is deprecated: Please see https://github.com/lydell/urix#deprecated
➤ YN0061: │ resolve-url@npm:0.2.1 is deprecated: https://github.com/lydell/resolve-url#deprecated
➤ YN0061: │ source-map-url@npm:0.4.1 is deprecated: See https://github.com/lydell/source-map-url#deprecated
➤ YN0061: │ @formatjs/intl-unified-numberformat@npm:2.2.0 is deprecated: We have renamed the package to @formatjs/intl-numberformat
➤ YN0061: │ @formatjs/intl-unified-numberformat@npm:3.3.7 is deprecated: We have renamed the package to @formatjs/intl-numberformat
➤ YN0061: │ core-js@npm:1.2.7 is deprecated: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
➤ YN0032: │ nan@npm:2.19.0: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ @babel/plugin-proposal-object-rest-spread@npm:7.12.1 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
➤ YN0032: │ evp_bytestokey@npm:1.0.3: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ abab@npm:2.0.6 is deprecated: Use your platform's native atob() and btoa() methods instead
➤ YN0061: │ domexception@npm:2.0.1 is deprecated: Use your platform's native DOMException instead
➤ YN0061: │ w3c-hr-time@npm:1.0.2 is deprecated: Use your platform's native performance.now() and performance.timeOrigin.
➤ YN0061: │ svgo@npm:1.3.2 is deprecated: This SVGO version is no longer supported. Upgrade to v2.x.x.
➤ YN0061: │ @formatjs/intl-utils@npm:2.3.0 is deprecated: the package is rather renamed to @formatjs/ecma-abstract with some changes in functionality (primarily selectUnit is removed and we don't plan to make any further changes to this package
➤ YN0061: │ @formatjs/intl-utils@npm:1.6.0 is deprecated: the package is rather renamed to @formatjs/ecma-abstract with some changes in functionality (primarily selectUnit is removed and we don't plan to make any further changes to this package
➤ YN0061: │ trim@npm:0.0.1 is deprecated: Use String.prototype.trim() instead
➤ YN0061: │ uuid@npm:3.4.0 is deprecated: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
➤ YN0002: │ @eeacms/volto-matomo@npm:4.2.1 doesn't provide react (pf9349), requested by @datapunt/matomo-tracker-react
➤ YN0002: │ @kitconcept/volto-slider-block@npm:6.3.0 [11772] doesn't provide embla-carousel (pe406e), requested by embla-carousel-autoplay
➤ YN0002: │ @kitconcept/volto-slider-block@npm:6.3.0 [11772] doesn't provide react (pb9662), requested by embla-carousel-react
➤ YN0002: │ @plone/volto@npm:18.0.0-alpha.23 doesn't provide @babel/runtime (pa8db0), requested by react-dates
➤ YN0002: │ @plone/volto@npm:18.0.0-alpha.23 doesn't provide @popperjs/core (pf7033), requested by react-popper
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides prop-types (pabf9c) with version 15.7.2, which doesn't satisfy what react-intl-redux requests
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react (pc0791) with version 18.2.0, which doesn't satisfy what react-router and some of its descendants request
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react (p8272a) with version 18.2.0, which doesn't satisfy what connected-react-router requests
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react (p99326) with version 18.2.0, which doesn't satisfy what react-beautiful-dnd and some of its descendants request
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react (p225de) with version 18.2.0, which doesn't satisfy what react-dates and some of its descendants request
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react (p9ee41) with version 18.2.0, which doesn't satisfy what react-detect-click-outside requests
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react (p059d1) with version 18.2.0, which doesn't satisfy what react-dnd and some of its descendants request
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react (pd1fc3) with version 18.2.0, which doesn't satisfy what react-image-gallery requests
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react (p5fe79) with version 18.2.0, which doesn't satisfy what react-intl requests
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react (p5911b) with version 18.2.0, which doesn't satisfy what react-medium-image-zoom requests
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react (p56756) with version 18.2.0, which doesn't satisfy what react-select-async-paginate and some of its descendants request
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react (p271e4) with version 18.2.0, which doesn't satisfy what react-select and some of its descendants request
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react (p58ba3) with version 18.2.0, which doesn't satisfy what react-share requests
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react (pb92b1) with version 18.2.0, which doesn't satisfy what react-simple-code-editor requests
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react (pe9649) with version 18.2.0, which doesn't satisfy what react-sortable-hoc requests
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react (p40055) with version 18.2.0, which doesn't satisfy what react-virtualized requests
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react (p80688) with version 18.2.0, which doesn't satisfy what redux-connect requests
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react-dom (pce947) with version 18.2.0, which doesn't satisfy what react-beautiful-dnd and some of its descendants request
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react-dom (pee425) with version 18.2.0, which doesn't satisfy what react-dates and some of its descendants request
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react-dom (p4e3e0) with version 18.2.0, which doesn't satisfy what react-detect-click-outside requests
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react-dom (p6814a) with version 18.2.0, which doesn't satisfy what react-medium-image-zoom requests
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react-dom (p73d84) with version 18.2.0, which doesn't satisfy what react-select requests
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react-dom (p40a5e) with version 18.2.0, which doesn't satisfy what react-simple-code-editor requests
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react-dom (pee16a) with version 18.2.0, which doesn't satisfy what react-sortable-hoc requests
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react-dom (pb9447) with version 18.2.0, which doesn't satisfy what react-virtualized requests
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react-redux (p81403) with version 8.1.2, which doesn't satisfy what connected-react-router requests
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react-redux (p68d25) with version 8.1.2, which doesn't satisfy what react-intl-redux requests
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides react-redux (pb3670) with version 8.1.2, which doesn't satisfy what redux-connect requests
➤ YN0060: │ @plone/volto@npm:18.0.0-alpha.23 provides redux-actions (p3afca) with version 3.0.0, which doesn't satisfy what redux-connect requests
➤ YN0002: │ @plone/volto@npm:18.0.0-alpha.23 doesn't provide seamless-immutable (p5283c), requested by connected-react-router
➤ YN0002: │ @storybook/addon-docs@npm:6.5.16 [3d275] doesn't provide @babel/core (p51740), requested by @babel/preset-env
➤ YN0002: │ @storybook/addon-docs@npm:6.5.16 [3d275] doesn't provide @babel/core (p5c48a), requested by @babel/plugin-transform-react-jsx
➤ YN0002: │ @storybook/addon-docs@npm:6.5.16 [3d275] doesn't provide @babel/core (p46fb2), requested by babel-loader
➤ YN0002: │ @storybook/addon-docs@npm:6.5.16 [3d275] doesn't provide webpack (p22d90), requested by babel-loader
➤ YN0002: │ @storybook/mdx1-csf@npm:0.0.1 doesn't provide @babel/core (p8e547), requested by @babel/preset-env
➤ YN0002: │ eslint-config-react-app@npm:7.0.1 [11772] doesn't provide @babel/plugin-syntax-flow (p390c6), requested by eslint-plugin-flowtype
➤ YN0002: │ eslint-config-react-app@npm:7.0.1 [11772] doesn't provide @babel/plugin-transform-react-jsx (p732aa), requested by eslint-plugin-flowtype
➤ YN0002: │ frontend@workspace:. doesn't provide @babel/core (pe41d0), requested by @storybook/addon-essentials
➤ YN0002: │ frontend@workspace:. doesn't provide babel-preset-razzle (p03705), requested by razzle
➤ YN0002: │ frontend@workspace:. doesn't provide eslint (p6cfce), requested by @typescript-eslint/eslint-plugin
➤ YN0002: │ frontend@workspace:. doesn't provide eslint (p9bb8b), requested by @typescript-eslint/parser
➤ YN0002: │ frontend@workspace:. doesn't provide html-webpack-plugin (p5447b), requested by razzle
➤ YN0002: │ frontend@workspace:. doesn't provide jest (pa0a1f), requested by ts-jest
➤ YN0002: │ frontend@workspace:. doesn't provide mini-css-extract-plugin (p29462), requested by razzle
➤ YN0002: │ frontend@workspace:. doesn't provide razzle-dev-utils (p2471a), requested by razzle
➤ YN0002: │ frontend@workspace:. doesn't provide react (pf85b9), requested by @storybook/builder-webpack5
➤ YN0002: │ frontend@workspace:. doesn't provide react (p0a951), requested by @storybook/manager-webpack5
➤ YN0002: │ frontend@workspace:. doesn't provide react (pe8283), requested by @storybook/react
➤ YN0002: │ frontend@workspace:. doesn't provide react-dom (p57e86), requested by @storybook/builder-webpack5
➤ YN0002: │ frontend@workspace:. doesn't provide react-dom (p6ce98), requested by @storybook/manager-webpack5
➤ YN0002: │ frontend@workspace:. doesn't provide react-dom (p35fb0), requested by @storybook/react
➤ YN0002: │ frontend@workspace:. doesn't provide require-from-string (p92bc6), requested by @storybook/react
➤ YN0060: │ frontend@workspace:. provides typescript (pdbdeb) with version 5.2.2, which doesn't satisfy what ts-jest requests
➤ YN0002: │ frontend@workspace:. doesn't provide webpack (pa465e), requested by razzle
➤ YN0002: │ frontend@workspace:. doesn't provide webpack (p3a7aa), requested by ts-loader
➤ YN0002: │ frontend@workspace:. doesn't provide webpack-dev-server (pc89af), requested by razzle
➤ YN0002: │ razzle@npm:4.2.18 [d9650] doesn't provide @babel/core (p8f413), requested by babel-loader
➤ YN0002: │ razzle@npm:4.2.18 [d9650] doesn't provide @babel/core (p3b79c), requested by babel-jest
➤ YN0002: │ rc-trigger@npm:2.6.5 doesn't provide react (p8a8f0), requested by rc-animate
➤ YN0002: │ rc-trigger@npm:2.6.5 doesn't provide react-dom (p1433f), requested by rc-animate
➤ YN0002: │ react-select-async-paginate@npm:0.5.3 [decea] doesn't provide react-dom (p994f3), requested by react-is-mounted-hook
➤ YN0002: │ volto-myproject@workspace:src/addons/volto-myproject doesn't provide @babel/core (p62c9a), requested by @babel/eslint-parser
➤ YN0002: │ volto-myproject@workspace:src/addons/volto-myproject doesn't provide @babel/plugin-syntax-flow (p83582), requested by eslint-plugin-flowtype
➤ YN0002: │ volto-myproject@workspace:src/addons/volto-myproject doesn't provide @babel/plugin-transform-react-jsx (p1453f), requested by eslint-plugin-flowtype
➤ YN0002: │ volto-myproject@workspace:src/addons/volto-myproject doesn't provide postcss (peab5e), requested by postcss-less
➤ YN0002: │ volto-myproject@workspace:src/addons/volto-myproject doesn't provide postcss (pdd1bd), requested by postcss-scss
➤ YN0002: │ volto-myproject@workspace:src/addons/volto-myproject doesn't provide postcss (pf9609), requested by stylelint-config-sass-guidelines
➤ YN0060: │ volto-myproject@workspace:src/addons/volto-myproject provides stylelint (pfcd01) with version 15.10.3, which doesn't satisfy what stylelint-config-idiomatic-order and some of its descendants request
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 22s 362ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yargs-parser@npm:21.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:15.4.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:16.2.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zwitch@npm:1.0.5 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 10s 881ms
➤ YN0000: ┌ Link step
➤ YN0007: │ frontend@workspace:. must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:3.36.1 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js-pure@npm:3.36.1 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:2.6.12 must be built because it never has been before or the last one failed
➤ YN0007: │ fsevents@patch:fsevents@npm%3A1.2.13#~builtin<compat/fsevents>::version=1.2.13&hash=18f3a7 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 10s 338ms
➤ YN0000: Done with warnings in 43s 823ms

```

But startup fails:
```
$ make start

make start
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'mini-css-extract-plugin'
Require stack:
- /Users/pbauer/workspace/test/myproject/frontend/node_modules/razzle/config/createConfigAsync.js
- /Users/pbauer/workspace/test/myproject/frontend/node_modules/razzle/scripts/start.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/Users/pbauer/workspace/test/myproject/frontend/node_modules/razzle/config/createConfigAsync.js:11:30)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/pbauer/workspace/test/myproject/frontend/node_modules/razzle/config/createConfigAsync.js',
    '/Users/pbauer/workspace/test/myproject/frontend/node_modules/razzle/scripts/start.js'
  ]
}

Node.js v18.18.2
make: *** [start] Error 1
```

**Comment by pbauer** [comment]
It still works with Volto 18.0.0-alpha.20 but fails since Volto 18.0.0-alpha.21

**Comment by stevepiercy** [comment]
From the [Volto Release Notes](https://6.docs.plone.org/volto/release-notes/index.html#alpha-22-2024-03-19):

> ## Documentation
> - Volto 18.0.0-alpha.21 and volto-update-deps documentation @sneridagh [#5892](https://github.com/plone/volto/issues/5892)

Which is rendered here:

https://6.docs.plone.org/volto/upgrade-guide/index.html#volto-s-internal-dependencies-and-devdependencies-are-now-properly-sorted-out

Does that help?

**Comment by sneridagh** [comment]
@pbauer something should be wrong in the cookiecutter side /cc @ericof 

There are tests in Volto core for testing that the build is ok. So what the generator outputs is correct. 
The cookiecutter template fiddles with some things from the generator output, so could be that it's something in need to be adapted.

@stevepiercy That is only needed for upgrading, not for newly created projects.

**Comment by sneridagh** [comment]
@pbauer confirmed, the generator alpha is correct and works well, to me, the cookiecutter is not enforcing the alpha version to be used when it's required.

**Comment by sneridagh** [comment]
Workaround: 

```
npm -g install @plone/generator-volto
yo @plone/volto my-volto-app --description "test volto project" --skip-install --no-interactive --canary```

**Comment by sneridagh** [comment]
So it seems that the problem is that the template is not able of getting generator versions beyond `@plone/generator-volto: "9.0.0-alpha.9"` :( probably a ordering bug...

**Comment by sneridagh** [comment]
@pbauer @stevepiercy https://github.com/collective/cookiecutter-plone-starter/pull/129

**Comment by sneridagh** [comment]
@pbauer @stevepiercy unfortunately that didn't make the trick, I got out of ideas: https://github.com/collective/cookiecutter-plone-starter/pull/130

**Comment by fredvd** [comment]
I'm running into the same issue, but with an already existing Volto 18 project that I'm upgrading from 18.0.0a12 -> to a23.  Am not running cookiecutter, just updating the versions and the running make install; make start.

**Comment by fredvd** [comment]
> I'm running into the same issue, but with an already existing Volto 18 project that I'm upgrading from 18.0.0a12 -> to a23. Am not running cookiecutter, just updating the versions and the running make install; make start.

After updating plone/scripts to 3.6.1 as well in my package.json . running `yarn` and running `yarn update-volto-deps` my project starts again.   Lesson, check the upgrade guide when using alpha versions.

**Comment by sneridagh** [comment]
@pbauer @stevepiercy @fredvd it's fixed now, thanks to @ericof !
