### ISSUE TITLE
When Updating volto to 6.0.0 getting babel error

### ISSUE THREAD

**Issue by iFlameing** [plone/volto#1710]
@tiberiuichim I am updating the volto from 5.8.0 to 6.0.0 I follow the upgrade guide
https://docs.voltocms.com/upgrade-guide/#upgrading-to-volto-6xx
I am getting this error
```bash
/home/iflameing/Documents/volto.kitconcept.dev/node_modules/resolve/lib/sync.js:74
    var err = new Error("Cannot find module '" + x + "' from '" + parent + "'");
              ^

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/plugin-proposal-function-bind' from '/home/iflameing/Documents/volto.kitconcept.dev'

   999 | /***/ (function(module, exports) {
  1000 | 
> 1001 | throw new Error("Module build failed (from ./node_modules/babel-loader/lib/index.js):\nError: Cannot find module '@babel/plugin-proposal-function-bind' from '/home/iflameing/Documents/volto.kitconcept.dev'\n    at Function.module.exports [as sync] (/home/iflameing/Documents/volto.kitconcept.dev/node_modules/resolve/lib/sync.js:74:15)\n    at resolveStandardizedName (/home/iflameing/Documents/volto.kitconcept.dev/node_modules/@babel/core/lib/config/files/plugins.js:101:31)\n    at resolvePlugin (/home/iflameing/Documents/volto.kitconcept.dev/node_modules/@babel/core/lib/config/files/plugins.js:54:10)\n    at loadPlugin (/home/iflameing/Documents/volto.kitconcept.dev/node_modules/@babel/core/lib/config/files/plugins.js:62:20)\n    at createDescriptor (/home/iflameing/Documents/volto.kitconcept.dev/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)\n    at /home/iflameing/Documents/volto.kitconcept.dev/node_modules/@babel/core/lib/config/config-descriptors.js:109:50\n    at Array.map (<anonymous>)\n    at createDescriptors (/home/iflameing/Documents/volto.kitconcept.dev/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)\n    at createPluginDescriptors (/home/iflameing/Documents/volto.kitconcept.dev/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)\n    at plugins (/home/iflameing/Documents/volto.kitconcept.dev/node_modules/@babel/core/lib/config/config-descriptors.js:40:19)");
  1002 | 
  1003 | /***/ }),
  1004 | 

    at Function.module.exports [as sync] (/home/iflameing/Documents/volto.kitconcept.dev/node_modules/resolve/lib/sync.js:74:15)
```

**Comment by tiberiuichim** [comment]
@iFlameing See https://docs.voltocms.com/upgrade-guide/#upgrading-to-volto-6xx

**Comment by tiberiuichim** [comment]
@iFlameing I suggest you copy yarn.lock from Volto 6.0 to your project, remove node_modules and run `yarn install --force`

**Comment by iFlameing** [comment]
@tiberiuichim I solved the issue but I have to install all the babel plugin which mentioned into babel.config.js in volto. I don't know why this is happening.

I don't know why it not resolving it from @plone/volto node_modules
```
  "dependencies": {
    "@babel/plugin-proposal-decorators": "7.10.5",
    "@babel/plugin-proposal-do-expressions": "7.10.4",
    "@babel/plugin-proposal-export-default-from": "7.10.4",
    "@babel/plugin-proposal-export-namespace-from": "7.10.4",
    "@babel/plugin-proposal-function-bind": "7.10.5",
    "@babel/plugin-proposal-function-sent": "7.10.4",
    "@babel/plugin-proposal-json-strings": "7.10.4",
    "@babel/plugin-proposal-logical-assignment-operators": "7.11.0",
    "@babel/plugin-proposal-nullish-coalescing-operator": "7.10.4",
    "@babel/plugin-proposal-numeric-separator": "7.10.4",
    "@babel/plugin-proposal-optional-chaining": "7.11.0",
    "@babel/plugin-proposal-pipeline-operator": "7.10.5",
    "@babel/plugin-proposal-throw-expressions": "7.10.4",
    "@babel/plugin-syntax-dynamic-import": "7.8.3",
    "@babel/plugin-syntax-import-meta": "7.10.4",
    "@plone/volto": "7.5.1"
  },
```

**Comment by tiberiuichim** [comment]
for the future reference, @sneridagh found that projects should add `@babel/core` as dependency (I think)
